/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F446XX.H"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIOA_CLK_EN();
	GPIOA->MODER &= ~(0x3 << (10));
	GPIOA->MODER |= (0x1 << 10);
	// Set output type to push-pull (default, bit 5 = 0)
	GPIOA->OTYPER &= ~(1 << 5);
	// Set output speed to medium (01)
	GPIOA->OSPEEDR &= ~(0x3 << 10);
	GPIOA->OSPEEDR |= (0x1 << 10);
	// No pull-up/pull-down (00)
	GPIOA->PUPDR &= ~(0x3 << 10);
	GPIOA->ODR |= (1<<5);
	//for(;;);
}
